[project]
name = "ofmt"
version = "1.1.1"
description = "Omni formatter. A formatter for everything."
requires-python = ">=3.11"
dependencies = []
readme = "readme.md"

[project.scripts]
ofmt = "ofmt:main"
